
server:
  tomcat:
    uri-encoding: UTF-8
  undertow:
    accesslog:
      dir: ./logs
      enabled: false
      pattern: common
      prefix: access_log
      rotate: true
      suffix: log

logging:
  config: classpath:logback.xml

eureka:
  client:
    service-url:
      defaultZone: http://www.bailuyiting.com:18650810243@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}

spring:
#  redis:
#    host: www.loveichong.com
#    port: 6379
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://bailuyiting.mysql.rds.aliyuncs.com:3306/loveichong?useUnicode=true&characterEncoding=gbk&zeroDateTimeBehavior=convertToNull&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: bailuyiting
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 18650810243 
    platform: mysql
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    filters: stat,wall,log4j
    logSlowSql: true
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: true
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

      
      
      
##################################################自定义配置###############################################
module:
    weChat:
          pay:
            mchID: 1499410362
            key: baiLUTingChe1581AQWE1917plmokATY
            appID: wx24151ca066138e3f
            appSecret: 735dea3575a1b49676447596f815f393
            spBillCreateIp: 192.168.1.113
            notifyIp: http://20b8052g92.iask.in:43200/sso
            certificateURI: D:/wechat/cert/apiclient_cert.p12
          mini:
            appID: wx001c84e3095353a9
            appSecret: de2004dc1f33378990ceda495dd16fc3
        
    KODO:
        endPoint: http://pcd1jyuhb.bkt.clouddn.com
        accessKeyId: wBaYc-q6rHaBkVxkj5-eNuS72D9We8G78MlX5ffm
        accessKeySecret: L45zsvZG8EWMIv2lan-ARhDdM7ARQcZaMQseFMyo
        bucketName: loveichong-publish

    Kdniao:
         businessID: 1372424
         appKey: 395c5af5-74a1-4adb-b520-512a962a55a9
         queryURL: http://api.kdniao.cc/Ebusiness/EbusinessOrderHandle.aspx



loveichong:
          accessTokenURL: http://localhost/sso/oauth/token










    

     
    



    
 