
server:
  tomcat:
    uri-encoding: UTF-8
  undertow:
    accesslog:
      dir: ./logs
      enabled: false
      pattern: common
      prefix: access_log
      rotate: true
      suffix: log

logging:
  config: classpath:logback.xml

eureka:
  client:
    service-url:
      defaultZone: http://www.bailuyiting.com:18650810243@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}

spring:
#  redis:
#    host: www.loveichong.com
#    port: 6379
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/loveichong?useUnicode=true&characterEncoding=gbk&zeroDateTimeBehavior=convertToNull&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 18650810243 
    platform: mysql
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    filters: stat,wall,log4j
    logSlowSql: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: true
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

      
      
      
##################################################自定义配置###############################################
module:
    weChat:
          pay:
            mchID: 1499410362
            key: baiLUTingChe1581AQWE1917plmokATY
            appID: wx24151ca066138e3f
            appSecret: 735dea3575a1b49676447596f815f393
            spBillCreateIp: 192.168.1.113
            notifyIp: http://20b8052g92.iask.in:43200/sso
            certificateURI: D:/wechat/cert/apiclient_cert.p12
          mini:
            appID: wx001c84e3095353a9
            appSecret: de2004dc1f33378990ceda495dd16fc3


    alipay:
          appID: 2018060560296716
          privateKey: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCbeKCTkTN4Liu2cuBZiJRknsiOwIDiwzlj3Ar+OrCv0WZearM8Dk/XE7G352TBj4yqMdE6VkGIONdsNVTs5TXcvEl4zeBPhyrEWU75LwJrKJHLM6iuvZVGcM4hDj612ngYG/uGAdNr5otqzSPmf6BcNAcTtibpP6jaAIGPHmRcCnpsUph0Gj7S5wro+BfXcP9H6B3zVE7QJLHo2pBWdY3dP5jkPIQu5BE6onU+hlpvjV3IFI1hdDkdEgM/TI29FUDUagerQjXHwhYpkTDOs+pmXsZamOx4LIa9XrdCD7mgb35NRBPoF2XcKtB64Q0MKZsPEo1V+hSBB2jfqDQm60E7AgMBAAECggEAdfCIP+nClcTQvFNhBgqqJ7qcgk5ed6eJfcuLO1jieD3t3morFb/1qT7zboNG199B4kpwYkTU6bXVFe1PQ3aN6amcQtxK8YmkU9c8JaQXvZrFHtVNfWGsQAeLF2BrCiF1QTTZFcuEyzHVSWvddBoVWFzPkZB47DCyss33es6fa4H/l01AjtdE622WQuje+5rgMv9wQjj+xnvsc0h6v3ypayv2wrppRtndkM1eyi3BaqlSGJXq1enDoVsq4MdClQvYkcPu4KllrchpHOwfdR+oQLW/VAEtjv2sI0By1gN2oE4ug1BScaTsN0e0VT5oQrkFAJ9KEwzqt/ZIwZfV3LztgQKBgQD+2MDdILFJyUkhOtkBlfQUM4JCiequR//1vSnFMzwNTimyR4WAcR65TGK22KPihGHu2qVkShzhFE2S08K6zsczXCWvk6WjNtxCX9F527XLrSYPkCK5m7qJqJIfjr/aYU9jWm2Vop8xsOg1tlwYS1luurgWIyRptKLwHD5QE4jJqwKBgQCcLL6njV7tfDSiBUrYhjCgxtTbq8UICMyLUZWTDVqI++RwADaCjOtSerSSbPzgODrA6g5mGa+n5LAGvLiAAX0hB1TBsKAP3Jn+r0vFsLIMWV+Z19OZFUa9SaCgutayWKlZXtAzvcejBVyz8/Crq1LsnVO3bbS+fA8dNdjz5Cl2sQKBgBdf1Bi0Fe65mo6EskC1+0QbEVh/A9pmWjC03+7paxmhUKu8aZ9FQNcoDWnN5wIwuDbLMR5IuetfDFpqN9Mggh7Q1dgLx8Z3kq430aPGph7/S51jz/uMMAjOQFDKrAggosJvGdv+pXFOU44RotLLnnFMiPPm10Emw0cYoBKCKCqvAoGAQ0xgx/D6lBnu0Fa5fv6sW8vyk8q8OA8anXqFmv2pIthxAvaEhtNU4JDx2RtQCQsR/mmd1M+CyzWXyP9v/fEmS6JOGr0S7GLilUZSv5i50Op+cNv5WcE6X30n07tPo0DjkRhzXaiNK6m23fDjqAZG0KGnHqcOuPraxHqcx9RtLbECgYEA8awd15G3iV+9udf9tOcbtTZjPqyFf9zpUJmYdnLJqdGUWVZZdB81TmARqLgdcQG0o24uAVIh2U+zNQQM7ONcWCddgYgcr+gHeyatmYCjRICBsLum2voGXD7xJtWbHDURXz0bLBH8lTNIgu/AKpNBr/nWoDojitbEbzTSnmWOqUE=
          publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAm3igk5EzeC4rtnLgWYiUZJ7IjsCA4sM5Y9wK/jqwr9FmXmqzPA5P1xOxt+dkwY+MqjHROlZBiDjXbDVU7OU13LxJeM3gT4cqxFlO+S8CayiRyzOorr2VRnDOIQ4+tdp4GBv7hgHTa+aLas0j5n+gXDQHE7Ym6T+o2gCBjx5kXAp6bFKYdBo+0ucK6PgX13D/R+gd81RO0CSx6NqQVnWN3T+Y5DyELuQROqJ1PoZab41dyBSNYXQ5HRIDP0yNvRVA1GoHq0I1x8IWKZEwzrPqZl7GWpjseCyGvV63Qg+5oG9+TUQT6Bdl3CrQeuENDCmbDxKNVfoUgQdo36g0JutBOwIDAQAB
          alipayPublicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAvT86vZaG6B2E4yGCzclq8rOdWpaYuPPYOYzHQ2258vDeH+1yTPq45a6N3NLjc9Z/K2lJHH745qPGnu5LDdlcIofdujG8QNvFZif/inTXcU3/HV/NNezH0oi9WAgd0b0QWjKizZn8Xur3nSTuKpNItBnt4+HbEm1lQkhBEuj7usgutsFhWEbm1BHpXHrFdok5gMSONfSaH/EC7KcmA9pNLrBubLLg8+8GqXR14MB+sE1YXSALV44mP3+mbUFVOx6VruQ3yG8cwmBzSiCEpvetTFQ23pMY7iygMckbgw/OSo63HC0/3u4hG0KlUp6WNaNmwjsmcfwdvw+/0VnBgVy5SQIDAQAB
          notifyIp: http://20b8052g92.iask.in:43200/sso

    OSS:
        endPoint: http://blyt.oss-cn-beijing.aliyuncs.com
        accessKeyId: LTAIpsiQiWIpN831
        accessKeySecret: eebo05VTtkqnXSdZPC2zjWl5GNNWOR
        bucketName: blyt
        
    KODO:
        endPoint: http://pcd1jyuhb.bkt.clouddn.com
        accessKeyId: wBaYc-q6rHaBkVxkj5-eNuS72D9We8G78MlX5ffm
        accessKeySecret: L45zsvZG8EWMIv2lan-ARhDdM7ARQcZaMQseFMyo
        bucketName: loveichong-publish

    Kdniao:
         businessID: 1372424
         appKey: 395c5af5-74a1-4adb-b520-512a962a55a9
         queryURL: http://api.kdniao.cc/Ebusiness/EbusinessOrderHandle.aspx



loveichong:
          accessTokenURL: http://localhost/sso/oauth/token










    

     
    



    
 